name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:
    inputs:
      version_string:
        description: 'Version of the package docs being deployed'
        type: string
        default: 'v0.0.0'
        required: true
  push:
    tags:
    - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Replace placeholder PACKAGE_VERSION string
      if: ${{ github.event_name == "push" }}
      run: |
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" setup.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" chess_scanparsers/__init__.py
        sed -i "s/PACKAGE_VERSION/${{ github.ref_name }}/" docs/conf.py

    - name: Replace placeholder PACKAGE_VERSION string
      if: ${{ github.event_name == "workflow_dispatch" }}
      run: |
        sed -i "s/PACKAGE_VERSION/${{ inputs.version_string }}/" setup.py
        sed -i "s/PACKAGE_VERSION/${{ inputs.version_string }}/" chess_scanparsers/__init__.py
        sed -i "s/PACKAGE_VERSION/${{ inputs.version_string }}/" docs/conf.py

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Build Sphinx documentation
      run: |
        make html
      working-directory: docs

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
